version: "3"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoapp
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    platform: linux/arm64

  mongo:
    image: arm64v8/mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    platform: linux/arm64

volumes:
  mongo-data:
